@startuml activity-min
start
:Получить кадровое событие;
if (Событие корректно?) then (да)
  :Создать идентичность;
else (нет)
  :Поместить в DLQ;
  stop
endif
fork
  :Назначить базовую роль;
fork again
  :Назначить роли по правилам;
end fork
:Запланировать создание учётных записей;
stop
@enduml
