// Импорт кейса IDM-JOINER: source/idm-joiner-docs/**/*.md → src/content/docs/case/**/*.mdx.
//
// Тексты не сокращаются и не переписываются. Меняется только разметка:
//   • H1 → title во frontmatter;
//   • пути в `бэктиках` → ссылки на страницы кейса, диаграммы, файлы, API;
//   • ID артефактов (FR-08, ADR-002…) → ссылки на место определения; там ставится якорь <span id="fr-08">;
//   • после строк «Диаграмма: …» вставляются PlantUmlDiagram / BpmnViewer;
//   • текст сериализуется через remark-mdx, поэтому { } < > экранируются корректно.
//
// Запуск: node scripts/import-case.mjs (результат коммитится; запускать заново после правок source/).
// Страницы, которых нет в source (обзор слоёв, «Все диаграммы», API, «Скачать»), пишутся вручную
// и этим скриптом не трогаются: он перезаписывает только файлы с пометкой GENERATED.
import { existsSync } from 'node:fs';
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { posix, join, relative, resolve, sep, dirname } from 'node:path';
import { unified } from 'unified';
import remarkParse from 'remark-parse';
import remarkGfm from 'remark-gfm';
import remarkMdx from 'remark-mdx';
import remarkStringify from 'remark-stringify';
import { toString } from 'mdast-util-to-string';
import { CASE_LAYERS } from '../src/case.mjs';

const SRC = resolve('source/idm-joiner-docs');
const OUT = resolve('src/content/docs/case');
const MARK = '{/* GENERATED by scripts/import-case.mjs из source/idm-joiner-docs — правки вносите в источник */}';
const toPosix = (p) => p.split(sep).join('/');

// ---------- Слои и страницы ----------

const LAYERS = Object.fromEntries(CASE_LAYERS.map((l) => [l.source, l]));

/** Короткие подписи для сайдбара (заголовки документов длинные). */
const SHORT = {
  '00_project/01_project-charter.md': 'Устав проекта',
  '00_project/02_stakeholders-raci.md': 'Стейкхолдеры и RACI',
  '00_project/03_glossary.md': 'Глоссарий проекта',
  '01_business/01_as-is.md': 'AS-IS',
  '01_business/02_to-be.md': 'TO-BE',
  '01_business/03_gap-analysis.md': 'Gap-анализ',
  '01_business/04_business-requirements.md': 'Бизнес-требования',
  '02_requirements/01_use-cases.md': 'Use cases',
  '02_requirements/02_functional-requirements.md': 'Функциональные требования',
  '02_requirements/03_non-functional-requirements.md': 'Нефункциональные требования',
  '02_requirements/04_role-model.md': 'Ролевая модель',
  '02_requirements/05_backlog.md': 'Бэклог',
  '02_requirements/06_traceability-matrix.md': 'Матрица трассировки',
  '03_architecture/01_context.md': 'Контекст (C4, L1)',
  '03_architecture/02_containers.md': 'Контейнеры (C4, L2)',
  '03_architecture/03_data-model.md': 'Модель данных',
  '03_architecture/04_state-models.md': 'Статусные модели',
  '03_architecture/05_adr.md': 'ADR',
  '04_integrations/01_integration-map.md': 'Карта интеграций',
  '04_integrations/02_scenarios.md': 'Сценарии (sequence)',
  '04_integrations/03_data-mapping.md': 'Маппинг данных',
  '05_security/01_security-requirements.md': 'Требования ИБ',
  '06_rollout/01_migration-strategy.md': 'Стратегия миграции',
  '06_rollout/02_rollout-plan.md': 'План внедрения',
  '06_rollout/03_release-plan.md': 'План релиза',
  '07_testing/01_test-program.md': 'ПМИ',
  '07_testing/02_test-cases.md': 'Тестовые сценарии',
  '08_operations/01_support-model.md': 'Модель сопровождения',
  '08_operations/02_runbook.md': 'Runbook',
  '08_operations/03_monitoring-alerting.md': 'Мониторинг и алерты',
  '08_operations/04_incident-example.md': 'Инцидент: учётные записи АБС не создаются',
  '08_operations/05_problem-rca.md': 'Проблема и анализ корневых причин',
  '08_operations/06_change-request.md': 'Запрос на изменение',
};

/** Слаг страницы сайта для исходного .md (без слэшей по краям). */
export function pageSlug(rel) {
  if (rel === 'README.md') return 'case';
  if (rel === 'CHEATSHEET.md') return 'case/cheatsheet';
  const [layer, file] = rel.split('/');
  return `case/${LAYERS[layer].dir}/${file.replace(/^\d+_/, '').replace(/\.md$/, '')}`;
}

/** Страницы API (пишутся вручную, см. src/content/docs/case/04-integrations/api-*.mdx). */
const API_PAGES = {
  '04_integrations/api/idm-api.openapi.yaml': 'case/04-integrations/api-idm',
  '04_integrations/api/abs-adapter.openapi.yaml': 'case/04-integrations/api-abs-adapter',
  '04_integrations/api/hr-events.asyncapi.yaml': 'case/04-integrations/api-hr-events',
};

// ---------- ID артефактов ----------

const ID_PREFIXES = ['G', 'R', 'P', 'BRL', 'GAP', 'BR', 'UC', 'FR', 'NFR', 'ENT', 'ROLE', 'RULE', 'SOD', 'EPIC', 'US', 'ADR', 'INT', 'SEQ', 'SEC', 'TC', 'ALR', 'RB', 'INC', 'PRB', 'CHG'];
const ID_RE = new RegExp(`(?<![A-Za-z0-9_-])((?:${ID_PREFIXES.join('|')})-\\d{1,3})(?![A-Za-z0-9_-]|\\.\\d)`, 'g');
const ID_FULL = new RegExp(`^(?:${ID_PREFIXES.join('|')})-\\d{1,3}$`);

/** В каком документе определяется ID каждого префикса (там ставится якорь). */
const HOME = {
  G: '00_project/01_project-charter.md',
  R: '00_project/01_project-charter.md',
  P: '01_business/01_as-is.md',
  BRL: '01_business/02_to-be.md',
  GAP: '01_business/03_gap-analysis.md',
  BR: '01_business/04_business-requirements.md',
  UC: '02_requirements/01_use-cases.md',
  FR: '02_requirements/02_functional-requirements.md',
  NFR: '02_requirements/03_non-functional-requirements.md',
  ENT: '02_requirements/04_role-model.md',
  ROLE: '02_requirements/04_role-model.md',
  RULE: '02_requirements/04_role-model.md',
  SOD: '02_requirements/04_role-model.md',
  EPIC: '02_requirements/05_backlog.md',
  US: '02_requirements/05_backlog.md',
  ADR: '03_architecture/05_adr.md',
  INT: '04_integrations/01_integration-map.md',
  SEQ: '04_integrations/02_scenarios.md',
  SEC: '05_security/01_security-requirements.md',
  TC: '07_testing/02_test-cases.md',
  ALR: '08_operations/03_monitoring-alerting.md',
  RB: '08_operations/02_runbook.md',
  INC: '08_operations/04_incident-example.md',
  PRB: '08_operations/05_problem-rca.md',
  CHG: '08_operations/06_change-request.md',
};

const anchorOf = (id) => id.toLowerCase();
const prefixOf = (id) => id.replace(/-\d+$/, '');

// ---------- Утилиты mdast ----------

function walk(node, fn, parents = []) {
  if (fn(node, parents) === false) return;
  if (node.children) for (const child of [...node.children]) walk(child, fn, [...parents, node]);
}

const jsxAttr = (name, value) => ({ type: 'mdxJsxAttribute', name, value });
const span = (id) => ({ type: 'mdxJsxTextElement', name: 'span', attributes: [jsxAttr('id', id), jsxAttr('class', 'case-anchor')], children: [] });

const processor = unified().use(remarkParse).use(remarkGfm);
const serializer = unified().use(remarkGfm).use(remarkMdx).use(remarkStringify, {
  bullet: '-',
  fences: true,
  rule: '-',
  emphasis: '_',
  strong: '*',
  listItemIndent: 'one',
});

async function walkFiles(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = await Promise.all(
    entries.map((e) => (e.isDirectory() ? walkFiles(join(dir, e.name)) : [join(dir, e.name)])),
  );
  return files.flat();
}

// ---------- Разрешение путей ----------

const allFiles = (await walkFiles(SRC)).map((f) => toPosix(relative(SRC, f)));
const byBase = new Map();
for (const f of allFiles) {
  const base = posix.basename(f);
  byBase.set(base, byBase.has(base) ? null : f); // null = неоднозначно
}

function resolveRef(value, docRel) {
  const v = value.trim();
  if (/[*?]/.test(v)) return null;
  const candidates = [posix.join(posix.dirname(docRel), v), posix.normalize(v)];
  for (const c of candidates) if (allFiles.includes(c)) return c;
  const base = byBase.get(posix.basename(v));
  return base ?? null;
}

export const diagramAnchor = (rel) => posix.basename(rel).replace(/\.(puml|bpmn)$/, '');

function urlForFile(rel) {
  if (rel.endsWith('.md')) return `/${pageSlug(rel)}/`;
  if (API_PAGES[rel]) return `/${API_PAGES[rel]}/`;
  if (rel.endsWith('.puml') || rel.endsWith('.bpmn')) return `/case/diagrams/#${diagramAnchor(rel)}`;
  return `/case-files/idm-joiner-docs/${rel}`;
}

// ---------- Проход 1: разбор и индекс ID ----------

const docs = allFiles.filter((f) => f.endsWith('.md'));
const trees = new Map();
/** id → { slug, anchor } */
const idIndex = new Map();
/** rel → Set(id) якоря, которые надо поставить в этом документе */

for (const rel of docs) {
  const tree = processor.parse(await readFile(join(SRC, rel), 'utf8'));
  trees.set(rel, tree);
}

for (const [rel, tree] of trees) {
  const slug = pageSlug(rel);
  // Заголовки, начинающиеся с ID: «## ADR-001. …», «## 3. UC-01. …», «### TC-12. …»
  walk(tree, (node) => {
    if (node.type !== 'heading' || node.depth < 2) return;
    const m = toString(node).match(new RegExp(`^(?:\\d+(?:\\.\\d+)*\\.?\\s*)?((?:${ID_PREFIXES.join('|')})-\\d{1,3})\\b`));
    if (!m || HOME[prefixOf(m[1])] !== rel || idIndex.has(m[1])) return;
    idIndex.set(m[1], { slug, anchor: anchorOf(m[1]) });
    node.children.unshift(span(anchorOf(m[1])));
    node.data = { ...node.data, anchored: m[1] };
  });
  // Первая ячейка строк таблиц
  walk(tree, (node) => {
    if (node.type !== 'table') return;
    node.children.slice(1).forEach((row) => {
      const cell = row.children[0];
      const text = toString(cell).trim();
      if (!ID_FULL.test(text) || HOME[prefixOf(text)] !== rel || idIndex.has(text)) return;
      idIndex.set(text, { slug, anchor: anchorOf(text) });
      cell.children.unshift(span(anchorOf(text)));
      cell.data = { ...cell.data, anchored: text };
    });
  });
}

// ---------- Проход 2: ссылки и диаграммы ----------

function linkIds(tree, rel) {
  walk(tree, (node, parents) => {
    if (node.type === 'heading' || node.type === 'link' || node.type === 'code' || node.type === 'inlineCode') return false;
    if (node.data?.anchored) return false; // ячейка-определение не ссылается сама на себя
    if (node.type !== 'text') return;
    const parent = parents.at(-1);
    const parts = [];
    let last = 0;
    for (const m of node.value.matchAll(ID_RE)) {
      const target = idIndex.get(m[1]);
      if (!target) continue;
      if (m.index > last) parts.push({ type: 'text', value: node.value.slice(last, m.index) });
      const url = target.slug === pageSlug(rel) ? `#${target.anchor}` : `/${target.slug}/#${target.anchor}`;
      parts.push({ type: 'link', url, children: [{ type: 'text', value: m[1] }] });
      last = m.index + m[1].length;
    }
    if (!parts.length) return;
    if (last < node.value.length) parts.push({ type: 'text', value: node.value.slice(last) });
    parent.children.splice(parent.children.indexOf(node), 1, ...parts);
  });
}

function linkPaths(tree, rel) {
  walk(tree, (node, parents) => {
    if (node.type === 'link' || node.type === 'heading') return false;
    if (node.type !== 'inlineCode') return;
    const target = resolveRef(node.value, rel);
    if (!target) return;
    const parent = parents.at(-1);
    const link = { type: 'link', url: urlForFile(target), children: [{ ...node }] };
    parent.children.splice(parent.children.indexOf(node), 1, link);
  });
}

function diagramNodes(refs) {
  const nodes = [];
  const svgs = new Set(refs.filter((r) => r.endsWith('.svg')));
  for (const r of refs) {
    if (r.endsWith('.puml')) {
      nodes.push({
        type: 'mdxJsxFlowElement',
        name: 'PlantUmlDiagram',
        attributes: [jsxAttr('file', r), jsxAttr('title', posix.basename(r))],
        children: [],
      });
    } else if (r.endsWith('.bpmn')) {
      const svg = r.replace(/\.bpmn$/, '.svg');
      const attrs = [
        jsxAttr('client:visible', null),
        jsxAttr('src', `/case-files/idm-joiner-docs/${r}`),
        jsxAttr('title', posix.basename(r)),
      ];
      if (svgs.has(svg) || allFiles.includes(svg)) attrs.push(jsxAttr('previewSrc', `/case-files/idm-joiner-docs/${svg}`));
      nodes.push({ type: 'mdxJsxFlowElement', name: 'BpmnViewer', attributes: attrs, children: [] });
    }
  }
  return nodes;
}

/** Вставляет диаграммы после абзацев «Диаграмма: …» и после таблицы сценариев SEQ. */
function insertDiagrams(tree, rel) {
  const used = { plantuml: false, bpmn: false };
  const children = tree.children;
  for (let i = 0; i < children.length; i++) {
    const node = children[i];
    let refs = [];
    if (node.type === 'paragraph' && /^Диаграмм[аы]:/.test(toString(node))) {
      walk(node, (n) => {
        if (n.type === 'inlineCode') {
          const t = resolveRef(n.value, rel);
          if (t) refs.push(t);
        }
      });
    } else if (node.type === 'table' && rel === '04_integrations/02_scenarios.md') {
      // Таблица SEQ: диаграмма на каждую строку, подпись — ID и описание сценария
      const nodes = node.children.slice(1).flatMap((row) => {
        const id = toString(row.children[0]).trim();
        const title = `${id}. ${toString(row.children[1]).trim()}`;
        let file = null;
        walk(row, (n) => {
          if (n.type === 'inlineCode' && !file) file = resolveRef(n.value, rel);
        });
        if (!file?.endsWith('.puml')) return [];
        used.plantuml = true;
        return [{ type: 'mdxJsxFlowElement', name: 'PlantUmlDiagram', attributes: [jsxAttr('file', file), jsxAttr('title', title)], children: [] }];
      });
      children.splice(i + 1, 0, ...nodes);
      i += nodes.length;
      continue;
    }
    if (!refs.length) continue;
    const nodes = diagramNodes(refs);
    if (nodes.some((n) => n.name === 'PlantUmlDiagram')) used.plantuml = true;
    if (nodes.some((n) => n.name === 'BpmnViewer')) used.bpmn = true;
    children.splice(i + 1, 0, ...nodes);
    i += nodes.length;
  }
  return used;
}

// ---------- Запись ----------

const yamlStr = (s) => JSON.stringify(s); // JSON-строка — валидный YAML

let written = 0;
for (const [rel, tree] of trees) {
  const h1Index = tree.children.findIndex((n) => n.type === 'heading' && n.depth === 1);
  const title = h1Index >= 0 ? toString(tree.children[h1Index]) : rel;
  if (h1Index >= 0) tree.children.splice(h1Index, 1);

  linkPaths(tree, rel);
  linkIds(tree, rel);
  const used = insertDiagrams(tree, rel);

  const slug = pageSlug(rel);
  const [layer, file] = rel.split('/');
  const order = rel === 'README.md' ? 0 : rel === 'CHEATSHEET.md' ? 1 : Number(file?.match(/^(\d+)_/)?.[1] ?? 99);
  const layerLabel = LAYERS[layer]?.label;
  const description =
    rel === 'README.md'
      ? 'Учебный кейс IDM-JOINER: полный комплект документации системного анализа — от устава до тест-кейсов.'
      : rel === 'CHEATSHEET.md'
        ? 'Шпаргалка к кейсу: слои проекта, этапы и артефакты, трассировка, карточки документов, разбор диаграмм.'
        : `Кейс IDM-JOINER · ${layerLabel}: ${title}.`;

  const frontmatter = [
    '---',
    `title: ${yamlStr(title)}`,
    `description: ${yamlStr(description)}`,
    'sidebar:',
    `  order: ${order}`,
    ...(SHORT[rel] ? [`  label: ${yamlStr(SHORT[rel])}`] : []),
    'tableOfContents:',
    '  maxHeadingLevel: 3',
    '---',
  ];

  // Путь импорта зависит от глубины файла: case/index.mdx → ../../../, case/cheatsheet.mdx → ../../../, case/x/y.mdx → ../../../../
  const depth = slug === 'case' ? 3 : slug.split('/').length + 1;
  const up = '../'.repeat(depth);
  const imports = [`import CaseSourceBar from '${up}components/case/CaseSourceBar.astro';`];
  if (used.plantuml) imports.push(`import PlantUmlDiagram from '${up}components/PlantUmlDiagram.astro';`);
  if (used.bpmn) imports.push(`import BpmnViewer from '${up}components/BpmnViewer.tsx';`);
  if (rel === 'README.md') imports.push(`import CaseLayers from '${up}components/case/CaseLayers.astro';`);

  const body = String(serializer.stringify(tree));
  const content = [
    ...frontmatter,
    '',
    ...imports,
    '',
    MARK,
    '',
    `<CaseSourceBar file="${rel}" />`,
    '',
    body.trim(),
    ...(rel === 'README.md' ? ['', '## Навигация по слоям', '', '<CaseLayers />'] : []),
    '',
  ].join('\n');

  const outFile = slug === 'case' ? join(OUT, 'index.mdx') : join(resolve('src/content/docs'), `${slug}.mdx`);
  if (existsSync(outFile)) {
    const prev = await readFile(outFile, 'utf8');
    if (!prev.includes('GENERATED by scripts/import-case.mjs')) {
      console.warn(`[import-case] пропущен (правлен вручную): ${outFile}`);
      continue;
    }
  }
  await mkdir(dirname(outFile), { recursive: true });
  await writeFile(outFile, content);
  written++;
}

console.log(`[import-case] страниц: ${written}, ID с якорями: ${idIndex.size}`);
