// Ранняя проверка MDX-страниц на частые ошибки, которые иначе ломают сборку с невнятным сообщением:
//   • «<слово» вне кода (MDX принимает за JSX-тег) — нужно \< или `код`;
//   • «{» вне кода (MDX принимает за выражение) — нужно \{ или `код`;
//   • «: » в title/description без кавычек (ломает YAML).
// Сгенерированные страницы кейса пропускаются: их экранирует scripts/import-case.mjs.
import { readFileSync, readdirSync } from 'node:fs';
import { join, sep } from 'node:path';

const ROOT = 'src/content/docs';

function walk(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
    e.isDirectory() ? walk(join(dir, e.name)) : [join(dir, e.name)],
  );
}

const problems = [];
for (const file of walk(ROOT).filter((f) => f.endsWith('.mdx'))) {
  const text = readFileSync(file, 'utf8');
  if (text.includes('GENERATED by scripts/import-case.mjs')) continue;
  const lines = text.split('\n');
  let inCode = false;
  let inFrontmatter = false;
  lines.forEach((line, i) => {
    const where = `${file.split(sep).join('/')}:${i + 1}`;
    if (i === 0 && line === '---') return (inFrontmatter = true);
    if (inFrontmatter) {
      if (line === '---') return (inFrontmatter = false);
      const m = line.match(/^(title|description):\s*(.*)$/);
      if (m && !/^["']/.test(m[2]) && /: /.test(m[2])) problems.push(`${where}: в ${m[1]} есть «: » — возьмите значение в кавычки`);
      return;
    }
    if (/^\s*```/.test(line)) return (inCode = !inCode);
    if (inCode) return;
    // Строки с JSX-компонентами и импортами проверять не нужно
    if (/^\s*(import |<\/?[A-Z]|<(div|section|p|ol|li|span|figure|ul|a)\b)/.test(line)) return;
    const plain = line.replace(/`[^`]*`/g, '');
    // Компоненты (<CaseRef>, <BpmnSymbol>) и HTML-теги начинаются с латиницы; «<» перед кириллицей — почти всегда текст
    if (/(^|[^\\])<[а-яёА-ЯЁ]/.test(plain)) {
      problems.push(`${where}: «<» перед буквой вне кода — экранируйте \\< или возьмите в \`код\``);
    }
    // «={» — проп компонента; строка, начинающаяся с «<» или «/>» — разметка компонента
    if (/(^|[^\\=])\{/.test(plain) && !/^\s*(<|\/>)/.test(line)) {
      problems.push(`${where}: «{» вне кода — экранируйте \\{ или возьмите в \`код\``);
    }
  });
}

if (problems.length) {
  console.error(`[lint-mdx] найдено проблем: ${problems.length}`);
  for (const p of problems) console.error(`  ✗ ${p}`);
  process.exit(1);
}
console.log('[lint-mdx] ок');
